from __future__ import annotations

from pathlib import Path
from typing import Any

from docx import Document

from ai_reviewer.ingest.types import ParsedDocument
from ai_reviewer.tools.docx_tools import (
    create_commented_docx_copy,
    create_docx_from_plain_text,
    validate_commented_docx,
)


def detect_source_mode(path: Path) -> dict[str, Any]:
    suffix = path.suffix.lower()
    if suffix == ".docx":
        return {"mode": "original_docx", "base_type": "docx"}
    if suffix == ".pdf":
        return {"mode": "pdf_only_surrogate", "base_type": "pdf"}
    return {"mode": "surrogate_other_source", "base_type": suffix.lstrip(".")}


def review_to_comment_entries(review: Any, max_comments: int = 32) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for idx, sec in enumerate(review.section_specific_comments, start=1):
        entries.append(
            {
                "paragraph_index": idx,
                "issue_type": "structure/organization",
                "severity": sec.severity,
                "critique": sec.comment,
                "suggested_revision": f"Revise section '{sec.section}' for clarity and precision.",
                "rationale": "Section-specific comment from review schema.",
            }
        )
    for idx, item in enumerate(review.extracted_action_items, start=len(entries) + 1):
        entries.append(
            {
                "paragraph_index": idx,
                "issue_type": "clarity",
                "severity": item.priority,
                "critique": item.action,
                "suggested_revision": f"Apply action: {item.action}",
                "rationale": "Action item generated by reviewer.",
            }
        )
        if len(entries) >= max_comments:
            break
    category_pairs = [
        ("methods concern", getattr(review, "methodological_concerns", [])),
        ("evidence/overclaim concern", getattr(review, "novelty_concerns", [])),
        ("citation/reference concern", getattr(review, "citation_reference_concerns", [])),
        ("grammar/style", getattr(review, "writing_organization_concerns", [])),
        ("formatting/journal style", getattr(review, "figure_table_concerns", [])),
        ("redundancy", getattr(review, "major_weaknesses", [])),
    ]
    for label, items in category_pairs:
        for item in items[:2]:
            entries.append(
                {
                    "paragraph_index": len(entries) + 1,
                    "issue_type": label,
                    "severity": "medium",
                    "critique": str(item),
                    "suggested_revision": "Revise wording to address this issue while preserving technical accuracy.",
                    "rationale": f"Derived from {label} findings.",
                }
            )
            if len(entries) >= max_comments:
                break
        if len(entries) >= max_comments:
            break
    if not entries:
        for idx, text in enumerate(review.detailed_reviewer_comments[:max_comments], start=1):
            entries.append(
                {
                    "paragraph_index": idx,
                    "issue_type": "grammar/style",
                    "severity": "medium",
                    "critique": text,
                    "suggested_revision": "Tighten wording while preserving technical meaning.",
                    "rationale": "Fallback from detailed reviewer comments.",
                }
            )
    if not entries:
        summary = str(getattr(review, "summary", "") or "").strip()
        weaknesses = [str(x) for x in getattr(review, "major_weaknesses", []) if str(x).strip()]
        seed = weaknesses[:3] or ([summary] if summary else [])
        if not seed:
            seed = [
                "Clarify core contribution and novelty claim.",
                "Tighten methods/result linkage language.",
                "Improve writing precision and remove ambiguous phrasing.",
            ]
        for idx, text in enumerate(seed, start=1):
            entries.append(
                {
                    "paragraph_index": idx,
                    "issue_type": "clarity",
                    "severity": "medium",
                    "critique": text,
                    "suggested_revision": "Revise this paragraph to be concrete and technically precise.",
                    "rationale": "Fallback comment when structured review fields were sparse.",
                }
            )
    return entries[:max_comments]


def _assign_paragraph_indices(entries: list[dict[str, Any]], base_docx: Path) -> list[dict[str, Any]]:
    doc = Document(str(base_docx))
    paragraphs = [p.text.strip() for p in doc.paragraphs]
    non_empty = [idx for idx, text in enumerate(paragraphs) if text]
    if not non_empty:
        return entries

    used: dict[int, int] = {}
    total = len(non_empty)
    for i, entry in enumerate(entries):
        critique = str(entry.get("critique", "")).lower()
        suggestion = str(entry.get("suggested_revision", "")).lower()
        anchor_terms = [w for w in (critique + " " + suggestion).split() if len(w) > 5][:12]

        chosen: int | None = None
        for pidx in non_empty:
            text = paragraphs[pidx].lower()
            if any(term in text for term in anchor_terms):
                if used.get(pidx, 0) < 2:
                    chosen = pidx
                    break

        if chosen is None:
            target_rank = max(0, min(total - 1, round((i + 1) * total / (len(entries) + 1))))
            chosen = non_empty[target_rank]
            attempts = 0
            while used.get(chosen, 0) >= 2 and attempts < total:
                target_rank = min(total - 1, target_rank + 1)
                chosen = non_empty[target_rank]
                attempts += 1

        entry["paragraph_index"] = chosen
        entry["paragraph_excerpt"] = paragraphs[chosen][:180]
        used[chosen] = used.get(chosen, 0) + 1
    return entries


def build_annotated_manuscript_output(
    source_path: Path,
    doc: ParsedDocument,
    review: Any,
    output_dir: Path,
) -> dict[str, Any]:
    source_mode = detect_source_mode(source_path)
    if source_mode["mode"] == "original_docx":
        base_docx = source_path
        reviewed_name = "reviewed_manuscript_with_comments.docx"
    else:
        base_docx = output_dir / "surrogate_manuscript_from_pdf_base.docx"
        create_docx_from_plain_text(doc.cleaned_text, base_docx, title=source_path.stem)
        reviewed_name = "surrogate_manuscript_from_pdf_with_comments.docx"
    comments = review_to_comment_entries(review)
    comments = _assign_paragraph_indices(comments, base_docx)
    reviewed_docx = output_dir / reviewed_name
    result = create_commented_docx_copy(base_docx, reviewed_docx, comments)
    validation = validate_commented_docx(base_docx, reviewed_docx)
    source_mode_artifact = {
        "project_id": None,
        "manuscript_source_path": str(source_path),
        "source_mode": source_mode["mode"],
        "surrogate_base_path": str(base_docx) if source_mode["mode"] != "original_docx" else None,
        "notes": [],
    }
    return {
        "source_mode": source_mode,
        "source_mode_artifact": source_mode_artifact,
        "base_docx": str(base_docx),
        "reviewed_docx": str(reviewed_docx),
        "comments_requested": len(comments),
        "comments_added": result.get("comments_added", 0),
        "anchored_paragraph_indices": result.get("anchored_paragraph_indices", []),
        "comment_targets": comments,
        "validation": validation,
    }
